apartmentTypes:
  V1:
    name: V1
    cost: 100
    block-icon: barrier
    schematic-file-name: V1
    permission: yes
    plotSize: small
  V3:
    name: V3
    cost: 100
    block-icon: barrier
    schematic-file-name: V3
    permission: yes
    plotSize: small
  V5:
    name: V5
    cost: 100
    block-icon: barrier
    schematic-file-name: V5
    permission: yes
    plotSize: small
  gov:
    name: gov
    cost: 100
    block-icon: barrier
    schematic-file-name: gov
    permission: Governor
    plotSize: FILL
  pres:
    name: pres
    cost: 100
    block-icon: barrier
    schematic-file-name: pres
    permission: President
    plotSize: FILL
  kingpin:
    name: kingpin
    cost: 100
    block-icon: barrier
    schematic-file-name: kingpin
    permission: Kingpin
    plotSize: FILL
  Emp:
    name: Emp
    cost: 100
    block-icon: barrier
    schematic-file-name: emp
    permission: Emperor
    plotSize: big
  house1:
    name: house1
    cost: 100
    block-icon: gold_block
    schematic-file-name: house1
    permission: none
    plotSize: small
  house2:
    name: house2
    cost: 100
    block-icon: barrier
    schematic-file-name: house2
    permission: none
    plotSize: FILL
  house3:
    name: house3
    cost: 100
    block-icon: barrier
    schematic-file-name: house3
    permission: none
    plotSize: small
  house4:
    name: house4
    cost: 100
    block-icon: barrier
    schematic-file-name: house4
    permission: none
    plotSize: FILL
  house5:
    name: house5
    cost: 100
    block-icon: barrier
    schematic-file-name: house5
    permission: none
    plotSize: small

defaultValues:
  # Decide what percentage of the original cost a player gets when selling their apartment
  returnOnSell: 50.0
